### ISSUE TITLE
Port should be optional when initializing a InfluxDBClient

### ISSUE THREAD

**Issue by Breee** [influxdata/influxdb-python#773]
- **InfluxDB version:** influxdb:latest

* Usecase:  Influxdb  behind a traefik. 

If I map my influxdb container to some domain `influx.example.com` 

e.g: 
```yaml
  sopra-influxdb:
    image: influxdb:latest
    environment:
       - something something
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
    networks:
      - default
      - proxy
    labels:
      - traefik.enable=false
      - traefik.docker.network=proxy
      - traefik.basic.frontend.rule=Host:influx.example.com
      - traefik.basic.frontend.port=8086
```
then i can't initialize the client like this: 

```python
client = InfluxDBClient(host='influx.example.com',
                 port=None,
                 username='write',
                 password='write',
                 database='some_db')
```

because `influx.example.com` already points to port 8086, so it is not necessary to pass a port
So the port should be optional imo :)
