### ISSUE TITLE
Authorization error against InfluxDB 2.0

### ISSUE THREAD

**Issue by rajahaidar** [influxdata/influxdb-python#897]
- **InfluxDB version:** 2.0
- **InfluxDB-python version:** e.g. 5.3.1
- **Python version:** 3.9
- **Operating system version:** Docker on MacOS

When upgrading influxDB from 1.8 to 2.0, and trying to use the same application logic we currently have, we are getting a 401 unauthorized when trying to insert data using the admin user which was specified in the upgrade environment variables.

```
Error raised: 401: {"code":"unauthorized","message":"Unauthorized"}
```

This is the docker-compose that was used to bring up the instance

```
  influxdb:
    image: influxdb:2.0
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb:/var/lib/influxdb
      - ./influxdb2:/var/lib/influxdb2

    networks:
      - backend
    environment:
      # - INFLUXDB_ADMIN_USER=admin
      # - INFLUXDB_ADMIN_PASSWORD=supersecret
      # - INFLUXDB_DB=db0
      - DOCKER_INFLUXDB_INIT_MODE=upgrade
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=supersecret
      - DOCKER_INFLUXDB_INIT_ORG=cnicc
      - DOCKER_INFLUXDB_INIT_BUCKET=default
```
